development:
  adapter: postgresql
  encoding: utf8
  database: test_shop_development
  username: root
  password: root
  host: localhost

staging:
  adapter: postgresql
  encoding: utf8
  database: test_shop_development
  username: root
  password: root
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: test_shop_test
  username: root
  password: root
  host: localhost