development:
  adapter: postgresql
  encoding: utf8
  database: test_shop_development
  username: root
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: test_shop_development
  username: root
  password: root
  host: localhost
