# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f67b402ac721ae1bff45cf3052fed0f6ae875ce4bc3baf2bd5415be3defe5ba21b05d776938a9eeb831ac0e47652b5f204ee67b04ee8ec8a89585f42c3fc2dfd

test:
  secret_key_base: 21fd293b5d5cd7713b0d5a1dbe3c73984fdb79022ceed8ac4168d1f31c40e9860d551d94e9a548129f04c036f1c40312d7b9682134bef7ba6dff6640e11cf807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
